### PR TITLE
Tweak attribute mapping

### LINKED ISSUE #3: crowd.user.get(username, true) does not work after last update
Basing on the error mesage, 

I checked the file : models/attributes.js   --->    attributesArr.forEach 
attributesArr is NOT an array so that do NOT have forEach function.

I print out attributesArr, it is an object, NOT an array.

### PR DESCRIPTION
**Pull request by alexashley**
- call the attributes mapper with the array of attributes, rather than an object containing the array in `CrowdClient.user.get` (closes #3)
- include the `attributesParser` and `attributesEncoder` in the `settings` property in the `CrowdApi` class 
- tweaked the example settings (removed the `crowd` key since the `CrowdApi` constructor [isn't doing any nested destructing](https://github.com/ghengeveld/atlassian-crowd-client/blob/master/src/api.js#L8) to get those values )

Let me know if there's anything I missed or you'd like something changed. Thanks again for the speedy response on my issue!

### CODE REVIEW

**Comment by alexashley** [comment]
sample response when calling `crowdClient.user.get(username, true)`

```javascript
User {
  firstname: 'test',
  lastname: 'test1',
  displayname: 'test test1',
  email: 'test@example.com',
  username: 'test1',
  password: undefined,
  active: true,
  attributes:
   { customAttribute: '0123',
     invalidPasswordAttempts: '0',
     lastActive: '123',
     lastAuthenticated: '123' } }
```

sample response calling `crowdClient.user.attributes.list `

```javascript
Attributes {
  attributes:
   { customAttribute: '0123',
     invalidPasswordAttempts: '0',
     lastActive: '123',
     lastAuthenticated: '123' } }
```

Given that  `crowdClient.user.get(username, true)` now returns an `Attributes` object, this is probably a breaking change

**Comment by ghengeveld** [comment]
Thanks for the improvement. I'm making some additional changes before I merge it and release it as v2.

**Comment by ghengeveld** [comment]
Released in [2.0.0](https://github.com/ghengeveld/atlassian-crowd-client/releases/tag/v2.0.0). Many thanks!

PS. Can you run the integration tests? I have no Crowd instance available anymore.

**Comment by alexashley** [comment]
@ghengeveld No problem, my current gig has a test Crowd instance I can run them against.

**Comment by alexashley** [comment]
@ghengeveld A few failures, seemed to mostly be related to the tests expecting an empty array of attributes and Crowd coming back with the default attributes.  

Here's the [log](https://github.com/ghengeveld/atlassian-crowd-client/files/1362996/test.log). I'd be happy to take a look into them over the weekend.

**Pull request merged**
